export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_RECIEVED = "MOVIE_RECIEVED";
export const API_ERROR = "API_ERROR";

// const MOVIE_REQUEST = "MOVIE_REQUEST";
// const MOVIE_REQUEST = "MOVIE_REQUEST";
// const MOVIE_REQUEST = "MOVIE_REQUEST";
// const MOVIE_REQUEST = "MOVIE_REQUEST";
// const MOVIE_REQUEST = "MOVIE_REQUEST";
