export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_RECIEVED = "MOVIE_RECIEVED";
export const API_ERROR = "API_ERROR";
export const SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_FALIURE = "SEARCH_MOVIE_FALIURE";
// const MOVIE_REQUEST = "MOVIE_REQUEST";
// const MOVIE_REQUEST = "MOVIE_REQUEST";
